version: "3.7"
services:
    db_events:
        image: postgres:latest
        # volumes: 
        #     - db_data:/var/lib/mysql
        restart: always
        environment:
            POSTGRES_DB: event_microservice
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: group24

        ports:
            - 3308:3308
    
    event:
        build: .
        image: event-service
        ports:
            - 3003:3000
        volumes:
            - .:/app
        depends_on:
            - db_events
        links:
            - db_events