development:
  primary:
    adapter: postgresql
    encoding: unicode
    host: db_events
    username: admin
    password: group24
    database: event_microservice
    port: 5432

test:
  primary:
    adapter: postgresql
    encoding: unicode
    host: db_events
    username: admin
    password: group24
    database: event_microservice
    port: 5432
